apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alloy
resources:
  - namespace.yaml
  - repository.yaml
  - chart.yaml

configMapGenerator:
  - name: alloy-values
    files:
      - values.yaml=values.yaml
  - name: alloy-config
    files:
      - config.alloy=config.alloy
    options:
      disableNameSuffixHash: true

