apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/monitoring/namespace.yaml
  - ../../base/monitoring/repository.yaml
  - ../../base/monitoring/controllers/kube-prometheus-stack
  - ../../base/monitoring/controllers/alloy
 # - ../../base/monitoring/controllers/loki