apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - chart.yaml

configMapGenerator:
  - name: alloy-values
    namespace: monitoring
    files:
      - values.yaml=values.yaml
  - name: alloy-config
    files:
      - config.alloy=config.alloy
    options:
      disableNameSuffixHash: true # prevent adding a hash to the configmap name on each deployment causing re-deployments

