apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nfs
  - kubevip
  - kubevip-cloud-controller
  - traefik
  - external-secrets-operator
  - cert-manager
  - external-dns
  - monitoring