apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mkped-wildcard-certificate
  namespace: traefik
spec:
  secretName: mkped-wildcard-certificate-secret
  issuerRef:
    name: cloudfare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - "*.mkped.com"
    - "mkped.com"
