# NOTE: These must be set manually to the control plane IP addresses
# kubeEtcd:
#  endpoints:
#    - x.y.z.a
#    - x.y.z.b
#    - x.y.z.c
# kubeControllerManager:
#   service:
#     selector:
#       k8s-app: kube-controller-manager
# kubeScheduler:
#   service:
#     selector:
#       k8s-app: kube-scheduler

alertmanager:
  enabled: false

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.mkped.com

    tls:
      - secretName: prometheus-certificate-secret
        hosts:
          - prometheus.mkped.com

  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring

    # Discover all PodMonitors, Probes, PrometheusRules and ServiceMonitors
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.mkped.com
    
    tls:
      - secretName: grafana-certificate-secret
        hosts:
          - grafana.mkped.com

  # persistence:
  #   enabled: true
  #   type: pvc
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 4Gi

  # Allow Omni Workload Proxying for this service
  # service:
  #   annotations:
  #     omni-kube-service-exposer.sidero.dev/port: "50082"
  #     omni-kube-service-exposer.sidero.dev/label: Grafana