alertmanager:
  enabled: false

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.mkped.com

    tls:
      - secretName: prometheus-certificate-secret
        hosts:
          - prometheus.mkped.com

  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring

    # Discover all PodMonitors, Probes, PrometheusRules and ServiceMonitors
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.mkped.com
    
    tls:
      - secretName: grafana-certificate-secret
        hosts:
          - grafana.mkped.com